2020-07-29 16:20:22,274 INFO  ==============================================================
2020-07-29 16:20:22,275 INFO  Id   : demo_1
2020-07-29 16:20:22,276 INFO  ==============================================================
2020-07-29 16:20:22,300 INFO  Started correlator<localhost:29560> with process id 21944
2020-07-29 16:20:22,874 INFO     Component correlator<pid 21944 on localhost:29560> is now running
2020-07-29 16:20:22,998 INFO  Executed engine_inject <correlator> [Asserts.mon], exit status 0
2020-07-29 16:20:23,114 INFO  Executed engine_inject <correlator> [test.mon], exit status 0
2020-07-29 16:20:23,226 INFO  Executed manage <correlator> [-r flushAllQueues], exit status 0
2020-07-29 16:20:23,289 INFO  Executed shutdown <correlator>, exit status 0
2020-07-29 16:20:23,378 WARN  Grep on correlator.log does not contain " ERROR " failed with: "2020-07-29 16:20:23.078 ERROR [14888] - AssertTest [1] FAILED floatEqualsTest - assert 4.54 = 4.55" ... failed [run.py:20]
2020-07-29 16:20:23,384 INFO  
2020-07-29 16:20:23,385 INFO  cleanup:
2020-07-29 16:20:23,386 INFO  
2020-07-29 16:20:23,386 INFO  Test duration: 1.11 secs
2020-07-29 16:20:23,387 INFO  Test final outcome:  FAILED
2020-07-29 16:20:23,387 INFO  Test outcome reason: Grep on correlator.log does not contain " ERROR " failed with: "2020-07-29 16:20:23.078 ERROR [14888] - AssertTest [1] FAILED floatEqualsTest - assert 4.54 = 4.55"
2020-07-29 16:20:23,392 INFO  
